sudo: required

dist: trusty

language: php
php:
  - '7.0'

services:
  - docker

before_install:
  - sudo sysctl -w vm.max_map_count=262144 # setting needed for elasticsearch
  - docker pull elasticsearch:6.4.2
  - docker run -d -p 127.0.0.1:9200:9200 --name elasticsearch elasticsearch:6.4.2

before_script:
  - cd ..
  - git clone https://github.com/drupal/drupal
  - ls -lah
  - ln -s ../../elasticentityquery drupal/modules/elasticentityquery
  - cd drupal
  - composer require elasticsearch/elasticsearch
  - composer install
  - cd core

script:
  - ../vendor/bin/phpunit --group=elasticentityquery --testsuite=unit
 
